### ISSUE TITLE
Config parser error after fresh config regen.

### ISSUE THREAD

**Issue by ChemicalDatas** [alkarinv/BattleArena#6] opened 2012-09-15 19:58 UTC
Ive deleted my config multiple times to have it regen.
Let me know if you need more info. 
Thanks.

2012-09-15 14:37:33 [INFO] [BattleArena] Enabling BattleArena v3.6.5.2
2012-09-15 14:37:33 [INFO] [BattleArena] v3.6.5.2 enabling!
2012-09-15 14:37:33 [INFO] [BattleArena] MassDisguise not detected, ignoring disguises
2012-09-15 14:37:33 [INFO] [BattleArena] Herochat not detected, ignoring Herochat channel options
2012-09-15 14:37:33 [INFO] BattleArena Loading arenas from C:\Vessel Craft MineCraft Server\Vessel Craft Minecraft Server\Vessel Craft Minecraft Server\plugins\BattleArena\arenas.yml using config 
2012-09-15 14:37:33 [INFO] [BattleArena] No arenas found
2012-09-15 14:37:33 [SEVERE] org.bukkit.configuration.InvalidConfigurationException: expected '<document start>', but found BlockMappingStart
 in "<string>", line 4, column 1:
    classes:
    ^

2012-09-15 14:37:33 [SEVERE]    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
2012-09-15 14:37:33 [SEVERE]    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:138)
2012-09-15 14:37:33 [SEVERE]    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:105)
2012-09-15 14:37:33 [SEVERE]    at mc.alk.arena.serializers.BaseSerializer.setConfig(BaseSerializer.java:45)
2012-09-15 14:37:33 [SEVERE]    at mc.alk.arena.BattleArena.onEnable(BattleArena.java:150)
2012-09-15 14:37:33 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
2012-09-15 14:37:33 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
2012-09-15 14:37:33 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
2012-09-15 14:37:33 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:265)
2012-09-15 14:37:33 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:247)
2012-09-15 14:37:33 [SEVERE]    at net.minecraft.server.MinecraftServer.i(MinecraftServer.java:296)
2012-09-15 14:37:33 [SEVERE]    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:275)
2012-09-15 14:37:33 [SEVERE]    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:225)
2012-09-15 14:37:33 [SEVERE]    at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:140)
2012-09-15 14:37:33 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:378)
2012-09-15 14:37:33 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
2012-09-15 14:37:33 [SEVERE] Caused by: expected '<document start>', but found BlockMappingStart
 in "<string>", line 4, column 1:
    classes:
    ^

2012-09-15 14:37:33 [SEVERE]    at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentStart.produce(ParserImpl.java:231)
2012-09-15 14:37:33 [SEVERE]    at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
2012-09-15 14:37:33 [SEVERE]    at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:146)
2012-09-15 14:37:33 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:109)
2012-09-15 14:37:33 [SEVERE]    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:121)
2012-09-15 14:37:33 [SEVERE]    at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480)
2012-09-15 14:37:33 [SEVERE]    at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)
2012-09-15 14:37:33 [SEVERE]    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53)
2012-09-15 14:37:33 [SEVERE]    ... 15 more
2012-09-15 14:37:33 [SEVERE] org.bukkit.configuration.InvalidConfigurationException: expected '<document start>', but found BlockMappingStart
 in "<string>", line 4, column 1:
    classes:
    ^

2012-09-15 14:37:33 [SEVERE]    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
2012-09-15 14:37:33 [SEVERE]    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:138)
2012-09-15 14:37:33 [SEVERE]    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:105)
2012-09-15 14:37:33 [SEVERE]    at mc.alk.arena.serializers.BAClassesSerializer.loadAll(BAClassesSerializer.java:18)
2012-09-15 14:37:33 [SEVERE]    at mc.alk.arena.BattleArena.onEnable(BattleArena.java:151)
2012-09-15 14:37:33 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
2012-09-15 14:37:33 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
2012-09-15 14:37:33 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
2012-09-15 14:37:33 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:265)
2012-09-15 14:37:33 [SEVERE]    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:247)
2012-09-15 14:37:33 [SEVERE]    at net.minecraft.server.MinecraftServer.i(MinecraftServer.java:296)
2012-09-15 14:37:33 [SEVERE]    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:275)
2012-09-15 14:37:33 [SEVERE]    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:225)
2012-09-15 14:37:33 [SEVERE]    at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:140)
2012-09-15 14:37:33 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:378)
2012-09-15 14:37:33 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
2012-09-15 14:37:33 [SEVERE] Caused by: expected '<document start>', but found BlockMappingStart
 in "<string>", line 4, column 1:
    classes:
    ^

2012-09-15 14:37:33 [SEVERE]    at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentStart.produce(ParserImpl.java:231)
2012-09-15 14:37:33 [SEVERE]    at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
2012-09-15 14:37:33 [SEVERE]    at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:146)
2012-09-15 14:37:33 [SEVERE]    at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:109)
2012-09-15 14:37:33 [SEVERE]    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:121)
2012-09-15 14:37:33 [SEVERE]    at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480)
2012-09-15 14:37:33 [SEVERE]    at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)
2012-09-15 14:37:33 [SEVERE]    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53)
2012-09-15 14:37:33 [SEVERE]    ... 15 more
2012-09-15 14:37:33 [INFO] [BattleArena] has no classes
2012-09-15 14:37:33 [INFO] BattleArena is now using BattleTracker interface 'arena'
2012-09-15 14:37:34 [SEVERE] Couldnt find arenaClass gladiator
2012-09-15 14:37:34 [INFO] [BattleArena] registering match =Arena:arena:Versus rating=RATED,nteams=2+,teamSize=1+,vc=LASTMANSTANDING
2012-09-15 14:37:34 [INFO] [BattleArena] registering match =Skirmish:skirmish:Versus rating=UNRATED,nteams=2+,teamSize=1+,vc=LASTMANSTANDING
2012-09-15 14:37:34 [INFO] BattleArena is now using BattleTracker interface 'col'
2012-09-15 14:37:34 [INFO] [BattleArena] registering match =Colliseum:col:Colliseum rating=RATED,nteams=4,teamSize=1,vc=LASTMANSTANDING
2012-09-15 14:37:34 [INFO] BattleArena is now using BattleTracker interface 'ffa'
2012-09-15 14:37:34 [INFO] [BattleArena] registering match =FreeForAll:ffa:FFA rating=RATED,nteams=2+,teamSize=1+,vc=LASTMANSTANDING
2012-09-15 14:37:34 [INFO] BattleArena is now using BattleTracker interface 'dm'
2012-09-15 14:37:34 [INFO] [BattleArena] registering match =DeathMatch:dm:DeathMatch rating=RATED,nteams=2+,teamSize=1+,vc=HIGHESTKILLS
2012-09-15 14:37:34 [INFO] BattleArena is now using BattleTracker interface 'tourney'
2012-09-15 14:37:34 [INFO] [BattleArena] registering match =Tourney:tourney:Versus rating=RATED,nteams=2+,teamSize=1+,vc=LASTMANSTANDING
2012-09-15 14:37:34 [INFO] BattleArena is now using BattleTracker interface 'bg'
2012-09-15 14:37:34 [SEVERE] Couldnt find arenaClass gladiator
2012-09-15 14:37:34 [INFO] [BattleArena] registering match =Battleground:bg:BattleGround rating=RATED,nteams=4,teamSize=1,vc=HIGHESTKILLS
2012-09-15 14:37:34 [INFO] [BattleArena] v3.6.5.2 enabled!
2012-09-15 14:37:34 [INFO] [BattleArena] found economy plugin Register
2012-09-15 14:37:34 [INFO] [BattleArena] found economy plugin Vault. [Default]

---

Heres the Config
ive switched arround the gladiator position to see if that made any diffrence in locatin it too.

version:1.1
### You can add new classes here

classes:
    archer:
        prettyName: "&4Archer" ### Used for signs
        items:
            - iron_sword: sharp:1 1
            - bow: flame:2 power:3 punch:2 1
            - arrow: 32
            - leather_helm: 1
            - iron_chest: prot:3 1
            - leather_leggings: 1
            - leather_boots: 1
            - 373;8229: 1 # potion of healing 2
            - 373;8193: 1 # potion of regen
            - 373;16396: 1 # splash potion of harming 1
    monk:
        prettyName: "&fMonk" ### Used for signs
        items:
            - leather_helm: 1
            - leather_chest: 1
            - leather_leggings: 1
            - leather_boots: 1
            - 373;8229: 2 # potion of healing 2
            - 373;8193: 2 # potion of regen
            - 373;16396: 3 # splash potion of harming 1
        enchants:
            - strength:3:900 # increase attack power
            - speed:2:900 # increase movement
            - haste:3:900 # increase attack speed
            - resistance:2:900 # reduce damage taken
            - jump:2:900 # jump 2 blocks higher than normal
            - regen:1:900 # regen life
    gladiator:
        prettyName: "&4Gladiator" ### Used for signs
        items:
            - diamond_sword: sharp:1 1
            - bow: 1
            - arrow: 32
            - diamond_helm: 1
            - diamond_chest: 1
            - diamond_leggings: 1
            - diamond_boots: 1
            - 373;8229: 1 # potion of healing 2
            - 373;8193: 1 # potion of regen
            - 373;16396: 1 # splash potion of harming 1
        enchants:
            - speed:1:900
            - resistance:1:900

**Comment by alkarinv** [comment] 2012-09-17 05:30
Ouch!!

Alright, so the issue is in the classes.yml file I had.

version:1.1
intead of
version: 1.1

Thats right.  Without the space you get half of those errors.

The other was b/c I was trying to read the messages.yml before it was created, which should be fixed on a 2nd start.

Both issues are now fixed in v3.6.5.3

Sorry about that.

You can download that one immediately here on Github. Or you can wait for it to clear bukkit

**Closed as completed by alkarinv** 2012-09-17 05:30 UTC
Labels: bug, Resolved
