### ISSUE TITLE
Latest Tourney Issue

### ISSUE THREAD

**Issue by freakyy85** [alkarinv/BattleArena#63] opened 2012-11-05 13:44 UTC
2012-11-05 14:38:23 [INFO] ^[[37;1m[Paintball Tourney] ^[[37;22mMr_Albe17^[[33;1m[1275] ^[[33;22m(1:0)^[[33;1m defeated ^[[37;22mFrostys_Flames^[[33;1m[1227] ^[[33;22m(1:2)!^[[m

At this point i got the message, final round freakyy85 vs Mr_Albe17 ... then suddenly this:

2012-11-05 14:38:48 [INFO] ^[[33;22m^[[37;1m[Paintball Tourney] Participants: TJ2418^[[33;1m, Mr_Albe17^[[33;1m, freakyy85 ^[[33;22m^[[m

And my next match was against TJ2418 and then the tourney was over or whatever, didnt announce any winner.

**Comment by alkarinv** [comment] 2012-11-05 14:49
How is your tourney doing this!! This is the same issue you were having before.  It's like a 3rd person can jump into any tourney match, which throws off how long it's supposed to take (because there are 2 people still left in the tournament... you and that 3rd person).  But b/c that 3rd person is not supposed to be there, it doesn't make the rounds correctly and never completes....

So I know what the issue is... I just don't know how it's happening yet...

**Comment by freakyy85** [comment] 2012-11-05 15:04
I don't know I also wondered where the 3rd player suddenly comes from.

**Comment by alkarinv** [comment] 2012-11-10 04:07
Should now be fixed in v3.7.2.1+... finally ;)

**Closed as completed by alkarinv** 2012-11-10 04:07 UTC
Labels: bug, Resolved
