### ISSUE TITLE
Leaving deathmatch

### ISSUE THREAD

**Issue by ondrajz** [alkarinv/BattleArena#69] opened 2012-11-19 18:31 UTC
Now, I haven't tested for other types of matches/events but for deathmatch there is this issue;
- when I join the match and leave I can't join back again (no I have not started it, it's still just opened)

**Comment by alkarinv** [comment] 2012-11-19 19:15
Hmm, Yeah I can see how that would be.  Does it say you are still in a match or something?  or just doesnt let you join?

**Comment by ondrajz** [comment] 2012-11-19 20:05
Says I am in the match. When I try to leave says I am not in the match.

**Comment by alkarinv** [comment] 2012-11-20 04:48
This should be fixed in v3.7.4.1+.  So going to close it for now, if the issue is still there open it back up :)

**Closed as completed by alkarinv** 2012-11-20 04:48 UTC
Labels: bug, Resolved
