### ISSUE TITLE
Arena Inventory Bug

### ISSUE THREAD

**Issue by joebladon** [alkarinv/BattleArena#18] opened 2012-09-28 22:04 UTC
If a player joins an arena and then disconnects from the server, when they log back in they are back at the point before they entered the arena but with the arena gear not their own inventory. This allows them to glitch free gear very easily.

**Comment by alkarinv** [comment] 2012-09-29 00:55
I can't reproduce this problem.  Can you pastebin me your config, or give me your server addess so I can come on and see it for myself?

I definitely believe you but I haven't heard of this glitch on other servers.

**Comment by joebladon** [comment] 2012-09-29 01:28
http://pastebin.com/Zpunk3Jy

Server is servers.citycraft.co.uk:1338

The user who reported it to me said they log out after taking damage and then it does it, not sure if that makes a difference.

**Comment by alkarinv** [comment] 2012-09-29 17:07
Well to start out with cool server!

I joined an arena.. got damaged, then logged out.  When I came back I had exactly what I started with before the arena.  I did this several times and I couldn't make this glitch happen.  Was it perhaps a one off? or is this happening to other players too?

**Comment by joebladon** [comment] 2012-09-29 18:58
Thanks :)

I have tested this method with a Mod from my server and have seen it work.
Here is the report on how they did it from my forums;

A player does /arena duel [username] and takes 1 hit from the other player.
You then logout and reconnect. On reconnecting it says in chat that you died and you have to click re-spawn on your client.
The arena inventory will now be on the floor at the point you were standing before entering the arena.

Sorry if i didn't make it clear it was a arena duel not just an arena. 

(Also if you were to do this with items in your inventory all these would be lost when you do it.)

**Comment by alkarinv** [comment] 2012-09-30 08:54
Ok. That makes things clear enough that I should be able to fix that problem.  So hopefully I'll have a fix tomorrow or the day after.

In the meantime put this in those configs you are using.  This will clear the items on death so nothing drops.  You shouldn't need to do this, but it should fix the problem straight away while I work out a real fix.

onDeath:
    options: [clearInventory]

Sorry about this Joe

**Comment by joebladon** [comment] 2012-09-30 13:59
It's no problem, it's great to finally find a dev who is as active as you and responds to reports in the same way.

**Comment by alkarinv** [comment] 2012-10-03 13:37
Well, I still can't reproduce this problem, I would really like to know what plugins you are using.  It must be some sort of strange conflict with one of them, because you have had more issues than any other server.

I'm going to close this for now as I can't make the bug happen, and I know you've taken out BattleArenas for your server, but let me know if you have ideas, or send me your plugin list. BattleArena's really should work for all servers, not just the majority!

**Closed as completed by alkarinv** 2012-10-03 13:37 UTC
Labels: bug
