### ISSUE TITLE
Logging out during arena

### ISSUE THREAD

**Issue by netherfoam** [alkarinv/BattleArena#21] opened 2012-09-30 06:09 UTC
Bukkit b2361 MC 1.3.2 
BattleArena v3.6.8

Plugins: BattleArena v3.6.8, BKCommonLib v1.24, Buycraft v4.7, ChestFix v0.6, DarekPlugin v0.2, DeathAndTaxes v0.2, dynmap v0.80-1304, EnchantShops v0.1.4, Essentials vPre2.9.4.2, EssentialsSpawn vPre2.9.4.2, FlatlandsBuilder v0.6.2, FlatSurvival v0.1, FreeSpace v0.1, GPPreciousStones v0.1, GriefPrevention v6.5, GriefPreventionCompat v0.2, HawkEye v1.0.7b, JukeboxControl v0.0.3, LevelUp v0.1, Lockette v1.6, MaxGamer v0.5, MaxPvP v0.1, mcMMO v1.3.11-b1030, mcMMOShop v0.1, MobCatcher v2.19 by Malikk, MultiInv v3.1.3, My Worlds v1.48, MyHelpPages v1.1, NoCheatPlus v3.7.3-b112, OpenInv v1.8.7, Orebfuscator v1.6.2, PermissionsEx v1.19.1, PingMOTD v0.0.5, PlugMan v1.7.2, PwnFilter v1.8, Questioner v0.6, QuickArena v0.1, QuickShop v1.9, Register v1.8, RemoteToolkitPlugin v0.61, Safe Creeper v1.0.1, SethomeProtection v0.1, SidewaysLogFix v1.01, SmartEco v0.1, SpaceBukkit v1.2, SpamDisconnectionFix v0.1, Spectate v1.9.1, Spout v1340, SpyKid v0.1, Stargate v0.7.7.2, TheEndAgain v0.99g, ThisLogMustDie v1.0, Tips v1.1, TowerControl v0.1, Towny v0.81.0.0, TownyChat v0.3, UltraBan v1.1.1, VanishNoPacket v3.12.1, Vault v5.2.17-b9001, VoidFix v0.1, Websend v1.5.1, WorldBorder v1.5.3, WorldEdit v1259-b4ac721, WorldGenerationControl v2.6, WorldGuard v${project.version}, xAuth v2.0.9

Logging out during a match is causing this error for me and DC'ing me with 'Internal Server Error'.  When I log back in, I'm in the arena still but have no items.

Notably, my arena is in a world called "arena" and my players are in a world called "challenge_7" so maybe it's a multiworld issue.

6:01:19 [INFO] wick issued server command: /r mebeh
06:01:25 [INFO] Pigheadtt issued server command: /r i have a bucket but not lave 1
06:01:27 [INFO] TestGuy124 lost connection: disconnect.quitting
06:01:27 [INFO] Connection reset
06:01:27 [INFO] [Arena] richie[0](0:0) defeated TestGuy124[0](0:0)!
06:01:27 [INFO] [NoCheatPlus] Milfa failed FastBreak: tried to break blocks faster than possible. VL 867.
06:01:29 [INFO] [G] [User] Pigheadtt: cbf
06:01:30 [INFO] Connection reset
06:01:32 [INFO] TestGuy124[/121.222.119.137:51450] logged in with entity id 1128232 at ([challenge_7] 300.39713455369997, 66.0, -302.80635497905314)
06:01:32 [INFO] [UltraBan] Logged TestGuy124 connecting from ip:121.222.119.137
06:01:32 [INFO] [VoidFix] TestGuy124: false
06:01:32 [INFO] [VoidFix] []
06:01:32 [INFO] Disconnecting TestGuy124 [/121.222.119.137:51450]: Internal server error
06:01:32 [WARNING] Failed to handle packet: java.lang.IllegalStateException: Failed to add player. EntityPlayer['TestGuy124'/1128232, l='arena', x=-111.65, y=54.00, z=154.48](TestGuy124 at -111.64759207191693,54.0,154.47654841677368) already is in chunk -15, 1
java.lang.IllegalStateException: Failed to add player. EntityPlayer['TestGuy124'/1128232, l='arena', x=-111.65, y=54.00, z=154.48](TestGuy124 at -111.64759207191693,54.0,154.47654841677368) already is in chunk -15, 1
        at net.minecraft.server.PlayerInstance.a(PlayerInstance.java:28)
        at net.minecraft.server.PlayerManager.addPlayer(PlayerManager.java:101)
        at net.minecraft.server.ServerConfigurationManagerAbstract.a(ServerConfigurationManagerAbstract.java:123)
        at net.minecraft.server.ServerConfigurationManagerAbstract.c(ServerConfigurationManagerAbstract.java:172)
        at net.minecraft.server.ServerConfigurationManagerAbstract.a(ServerConfigurationManagerAbstract.java:92)
        at net.minecraft.server.NetLoginHandler.d(NetLoginHandler.java:121)
        at net.minecraft.server.NetLoginHandler.c(NetLoginHandler.java:41)
        at net.minecraft.server.DedicatedServerConnectionThread.a(DedicatedServerConnectionThread.java:44)
        at net.minecraft.server.DedicatedServerConnection.b(SourceFile:29)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:578)
        at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
        at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
06:01:33 [INFO] TestGuy124 lost connection: disconnect.endOfStream
06:01:34 [INFO] [NoCheatPlus] Milfa failed FastBreak: tried to break blocks faster than possible. VL 677.
06:01:35 [INFO] wick issued server command: /r I've killed everyone b4 tho... lol

**Comment by alkarinv** [comment] 2012-09-30 09:08
Thanks for the code update, I'll put that fix in as soon as I find out how to merge github branches. Or I'll just change that line.

**Comment by alkarinv** [comment] 2012-09-30 09:11
Also, I need to make a special thread about this error.  That error is a Multiverse bug, Multiverse does something where it thinks that if a player logs out in a different world, then logs back in, that they have never left and throws some sort of strange error.  This error doesnt show up until bukkit throws the exception you see above.  What this means is that the player gets disconnected, but is still thought to be "online" on the server.  You can imagine that if the server thinks a player is online when they really aren't that it can cause a lot of issues.

**Comment by netherfoam** [comment] 2012-09-30 10:49
I'm using MyWorlds not Multiverse, but I've encountered this issue before and know it's a pain

**Comment by Fronix** [comment] 2012-09-30 14:56
This happens for me as well and I'm also using MyWorlds

http://pastebin.com/yx43QSGD

**Comment by alkarinv** [comment] 2012-09-30 23:13
Hey Fronix, that is a different error(one that really is mine), which I just fixed in the code.

I haven't heard of MyWorlds but if it does something similar then maybe its actually a minecraft/bukkit bug that only happens with those 2 plugins b/c of the different worlds.  Anyway, as I said, after this bug happens bukkit literally thinks the player is online, and so my code acts like they are online as well... not sure how to get around it.

**Comment by alkarinv** [comment] 2012-10-01 01:53
I'm going to close this as it's not a BattleArena bug.  But if you can think of any ways to avoid it I would be happy to try workarounds ( but my current attempts have failed )

**Closed as completed by alkarinv** 2012-10-01 01:53 UTC
Labels: bug, Resolved

**Comment by netherfoam** [comment] 2012-10-01 06:11
I don't know a lot here, but could you try schedule a task a few ticks after login to fix it up?

Just a thought.

**Comment by alkarinv** [comment] 2012-10-01 06:45
I've scheduled it from 1 tick up to 1 minute afterwards.  Problem is bukkit thinks the person is "online".  Until the player logs back in the server happily continues thinking the player is still around in that chunk.  At some point it finally realizes there is no one there, but its a really long time.

Maybe I can try refreshing that chunk to see if that would get bukkit to realize they really aren't there....

**Comment by netherfoam** [comment] 2012-10-01 06:56
Maybe there's a plugin holding onto the players instance after they've logged off, meaning it cant be sent to the garbage collector? (Thus, they're still in the world and all, bukkit has just said they're quitting and then can't force them to quit because something is still holding onto it...)

I know some guy had a rant signature on the forums as to why its a bad idea to store a player in a hashmap, list, set, etc, anything really.  Because bukkit cant release it anymore and it wastes memory... Maybe it does this too?

**Comment by alkarinv** [comment] 2012-10-01 07:24
Thats a good point.  I don't think that's the issue but it could be.  The reason I think it's probably not is that even if a Player can not be garbage collected because some other plugin is holding onto the object, doesn't mean that bukkit needs to use that object.  So it would definitely be a waste of memory as java couldn't collect the player, but bukkit could have moved on to the newer Player object.

**Comment by netherfoam** [comment] 2012-10-01 12:39
Well its an idea, if you disabled everything else (plugin wise) and tried?

Unless BattleArena is storing player instances somewhere?

Just throwing it out there

**Comment by netherfoam** [comment] 2012-10-01 22:04
Or, what about this.

I know xAuth used to have a bug where when a player was teleported to the spawn of the world, they would be given the same internal srver error.  That happened because either a player was quitting and xauth was teleporting them (this only happened if they were in a diff world to the spawn/destination of the tp)  or when they were joining, xauth would teleport them to the spawn.  I dont know which actions or way xauth did it, but it generated e same error.  Can i suggest checking the teleports on logout/login?

**Comment by netherfoam** [comment] 2012-10-01 22:06
I realise thats a bit muddled but:
- Teleporting onQuitEvent may cause it?
- Teleporting onJoin may cause it?

In each case, the teleport has to be to a different world to bug it.

</hypothesis>

**Comment by alkarinv** [comment] 2012-10-01 22:49
Ok, I was wrong about mulitverse.  Your last comment was correct.. It was Teleporting onJoin that was the root cause of the issue.  I updated that so that it happens on the tick after, and no more error.

In other news.... I now think you are amazing :)  Without you pressing on this issue I don't think I would have found out the real reason, I was convinced it was a multiverse bug.

**Comment by alkarinv** [comment] 2012-10-01 22:49
I'll release the version with a fix soon.

**Comment by netherfoam** [comment] 2012-10-02 01:22
Wooot :)

I did nothing, you coded it lol.

**Comment by netherfoam** [comment] 2012-10-02 06:45
Waiting on the fix when you're ready :-)

**Comment by alkarinv** [comment] 2012-10-02 06:56
It's currently up on bukkit, you will probably need a subscription to see it until it clears.

Could you let me know if this fixes the other inventory bug you were having?

Trying to nail all of these down!

**Comment by netherfoam** [comment] 2012-10-02 10:38
Ill come back if I manage to reproduce it :)

**Comment by netherfoam** [comment] 2012-10-03 03:06
So, the strangest thing is happening. I cant reproduce it without HeroChat, BattleArena and NoCheatPlus.

NoCheatPlus seems to be attempting to do exactly what you tried to do (Except not multiworld, so apparently it's okay) in teleporting onJoin.  But this throws a NPE from herochat and (sometimes) myworlds too. Also the same internal server exception _afterwards_.

I only get this after relogging in a battleground.

I don't know if you know anything about it, but I'm going to comment out a NCP line for the onJoin and it seems to fix it.

Disabling NCP or herochat fixes the problem it seems.  (Though, I'm keen to blame NCP for that teleport)

**Comment by alkarinv** [comment] 2012-10-03 05:53
Well bukkit hasn't put up the new version for some reason still (it's been 24+ hours at this point).  Do you have version 3.6.8.2?  Because that release fixes the line that teleports onJoin.  Hopefully thats it because I feel like this is the same issue.

**Comment by netherfoam** [comment] 2012-10-03 06:42
Yeah, I compiled from github.

I think it's caused by NoCheat, so I don't _think_ its something you have to worry about.  Just that BattleArena is revealing NoCheat for its mistake.

**Comment by netherfoam** [comment] 2012-10-03 06:43
And I can see why It'd take a while to approve, damn, this is a big project. :O

**Comment by alkarinv** [comment] 2012-10-03 13:27
Ok, good to know its not Arenas.  

lol, yeah it is a bit large :)  Theres just a lot of things I wanted to do.  The good side is that if you want to make a new match/event that code is very simple, you can check out ArenaPaintball or ArenaSpleef, both are very small.
