### ISSUE TITLE
Battle Grounds Causing Server Lockup

### ISSUE THREAD

**Issue by joebladon** [alkarinv/BattleArena#22] opened 2012-09-30 14:18 UTC
Ok so i'm 99% sure that battlearena is causing this, if i'm wrong i'm sorry for reporting it. What i've been experiencing since adding battlearena to my server is server lockups were the server stops accepting commands, chunks stop loading and the server becomes unreachable for people trying to connect. However chat still continues to work for those logged in until eventually craftbukkit reports in console that it's become unresponsive.
I have never experienced this before adding the plugin to the server and now it is causing 5-6 crashes a day. I can't see any error messages in console when this happens but what i can see is that battlegrounds seem to be happening at the point of the lockup. I have been in-game, in a bg 2 times when this has happened.
I've tried everything possible to find out what is causing this other than battlearena as the players are really loving it! But sadly this is the only thing left that i can see to be causing this and i have now had to remove the plugin in hope that it can be fixed.

If you don't see a way that battlearena could be causing this then i am sorry for reporting this to you.

Also another little thing, if you set bg to disabled in the config it still allows people to join. You have to type the command in-game to actually disable it. Even then people can still /bg duel [player].

_EDIT_ My server has been running without crashing for the past day now that the plugin has been removed. Just a little more evidence to show that battlearena could be the cause.

**Comment by alkarinv** [comment] 2012-09-30 21:14
I have no idea how BattleArena can be causing this.  It's been used on the server I've been playing on for the last 9-12 months without any sign of lockups like this.

It's also being used by many other servers and I have never heard of any bug that causes crashes.  The worst I've heard is occasional inventory glitches.

I will definitely check, but I just don't see how it could cause such serious issues.  I listen to bukkit events just like any other plugin, but besides this nothing that would cause something of this magnitude.

**Comment by alkarinv** [comment] 2012-10-01 01:49
So i've checked with some other people I know running servers with BattleArena, 11 servers.  None of them have had a similar issue.  On battlecraft, since 2012-08-24, there have been 35,000 arena matches with no server lag/crashes from battlearena.  I also rechecked the code to make sure there werent any extra threads being created that weren't closed, or any other extra memory being created.

Basically I've tried to figure out if it's the cause, but I just don't see it.  Maybe there is something with another of your plugins doing something that is interferring with BattleArena? maybe pastebin me, or pm me, your plugin list and I'll check that out.  Until then though I'm going to close this as invalid.

**Closed as completed by alkarinv** 2012-10-01 01:49 UTC
Labels: invalid, Resolved
